package com.tryfinch.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class EmploymentDataResponseTest {

    @Test
    fun createEmploymentDataResponse() {
        val employmentDataResponse =
            EmploymentDataResponse.builder()
                .individualId("string")
                .code(123L)
                .body(
                    EmploymentData.builder()
                        .id("string")
                        .firstName("string")
                        .middleName("string")
                        .lastName("string")
                        .title("string")
                        .manager(
                            EmploymentData.Manager.builder()
                                .id("e8b90071-0c11-471c-86e8-e303ef2f6782")
                                .build()
                        )
                        .department(EmploymentData.Department.builder().name("string").build())
                        .employment(
                            EmploymentData.Employment.builder()
                                .type(EmploymentData.Employment.Type.EMPLOYEE)
                                .subtype(EmploymentData.Employment.Subtype.FULL_TIME)
                                .build()
                        )
                        .startDate("string")
                        .endDate("string")
                        .isActive(true)
                        .classCode("string")
                        .location(
                            Location.builder()
                                .line1("string")
                                .line2("string")
                                .city("string")
                                .state("string")
                                .postalCode("string")
                                .country("string")
                                .name("string")
                                .sourceId("string")
                                .build()
                        )
                        .income(
                            Income.builder()
                                .unit(Income.Unit.YEARLY)
                                .amount(123L)
                                .currency("string")
                                .effectiveDate("string")
                                .build()
                        )
                        .incomeHistory(
                            listOf(
                                Income.builder()
                                    .unit(Income.Unit.YEARLY)
                                    .amount(123L)
                                    .currency("string")
                                    .effectiveDate("string")
                                    .build()
                            )
                        )
                        .workId("string")
                        .workId_2("string")
                        .payGroupIds(listOf("string"))
                        .build()
                )
                .build()
        assertThat(employmentDataResponse).isNotNull
        assertThat(employmentDataResponse.individualId()).contains("string")
        assertThat(employmentDataResponse.code()).contains(123L)
        assertThat(employmentDataResponse.body())
            .contains(
                EmploymentData.builder()
                    .id("string")
                    .firstName("string")
                    .middleName("string")
                    .lastName("string")
                    .title("string")
                    .manager(
                        EmploymentData.Manager.builder()
                            .id("e8b90071-0c11-471c-86e8-e303ef2f6782")
                            .build()
                    )
                    .department(EmploymentData.Department.builder().name("string").build())
                    .employment(
                        EmploymentData.Employment.builder()
                            .type(EmploymentData.Employment.Type.EMPLOYEE)
                            .subtype(EmploymentData.Employment.Subtype.FULL_TIME)
                            .build()
                    )
                    .startDate("string")
                    .endDate("string")
                    .isActive(true)
                    .classCode("string")
                    .location(
                        Location.builder()
                            .line1("string")
                            .line2("string")
                            .city("string")
                            .state("string")
                            .postalCode("string")
                            .country("string")
                            .name("string")
                            .sourceId("string")
                            .build()
                    )
                    .income(
                        Income.builder()
                            .unit(Income.Unit.YEARLY)
                            .amount(123L)
                            .currency("string")
                            .effectiveDate("string")
                            .build()
                    )
                    .incomeHistory(
                        listOf(
                            Income.builder()
                                .unit(Income.Unit.YEARLY)
                                .amount(123L)
                                .currency("string")
                                .effectiveDate("string")
                                .build()
                        )
                    )
                    .workId("string")
                    .workId_2("string")
                    .payGroupIds(listOf("string"))
                    .build()
            )
    }
}
