// File generated from our OpenAPI spec by Stainless.

package com.tryfinch.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.tryfinch.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EmploymentDataResponseTest {

    @Test
    fun create() {
        val employmentDataResponse =
            EmploymentDataResponse.builder()
                .body(
                    EmploymentData.UnionMember0.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .classCode("class_code")
                        .addCustomField(
                            EmploymentData.UnionMember0.CustomField.builder()
                                .name("name")
                                .value("string")
                                .build()
                        )
                        .department(
                            EmploymentData.UnionMember0.Department.builder().name("name").build()
                        )
                        .employment(
                            EmploymentData.UnionMember0.Employment.builder()
                                .subtype(EmploymentData.UnionMember0.Employment.Subtype.FULL_TIME)
                                .type(EmploymentData.UnionMember0.Employment.Type.EMPLOYEE)
                                .build()
                        )
                        .employmentStatus(EmploymentData.UnionMember0.EmploymentStatus.ACTIVE)
                        .endDate("end_date")
                        .firstName("first_name")
                        .isActive(true)
                        .lastName("last_name")
                        .latestRehireDate("latest_rehire_date")
                        .location(
                            Location.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .name("name")
                                .sourceId("source_id")
                                .build()
                        )
                        .manager(
                            EmploymentData.UnionMember0.Manager.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .middleName("middle_name")
                        .sourceId("source_id")
                        .startDate("start_date")
                        .title("title")
                        .workId("work_id")
                        .income(
                            Income.builder()
                                .amount(0L)
                                .currency("currency")
                                .effectiveDate("effective_date")
                                .unit(Income.Unit.YEARLY)
                                .build()
                        )
                        .addIncomeHistory(
                            Income.builder()
                                .amount(0L)
                                .currency("currency")
                                .effectiveDate("effective_date")
                                .unit(Income.Unit.YEARLY)
                                .build()
                        )
                        .build()
                )
                .code(0L)
                .individualId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .build()

        assertThat(employmentDataResponse.body())
            .isEqualTo(
                EmploymentData.ofUnionMember0(
                    EmploymentData.UnionMember0.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .classCode("class_code")
                        .addCustomField(
                            EmploymentData.UnionMember0.CustomField.builder()
                                .name("name")
                                .value("string")
                                .build()
                        )
                        .department(
                            EmploymentData.UnionMember0.Department.builder().name("name").build()
                        )
                        .employment(
                            EmploymentData.UnionMember0.Employment.builder()
                                .subtype(EmploymentData.UnionMember0.Employment.Subtype.FULL_TIME)
                                .type(EmploymentData.UnionMember0.Employment.Type.EMPLOYEE)
                                .build()
                        )
                        .employmentStatus(EmploymentData.UnionMember0.EmploymentStatus.ACTIVE)
                        .endDate("end_date")
                        .firstName("first_name")
                        .isActive(true)
                        .lastName("last_name")
                        .latestRehireDate("latest_rehire_date")
                        .location(
                            Location.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .name("name")
                                .sourceId("source_id")
                                .build()
                        )
                        .manager(
                            EmploymentData.UnionMember0.Manager.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .middleName("middle_name")
                        .sourceId("source_id")
                        .startDate("start_date")
                        .title("title")
                        .workId("work_id")
                        .income(
                            Income.builder()
                                .amount(0L)
                                .currency("currency")
                                .effectiveDate("effective_date")
                                .unit(Income.Unit.YEARLY)
                                .build()
                        )
                        .addIncomeHistory(
                            Income.builder()
                                .amount(0L)
                                .currency("currency")
                                .effectiveDate("effective_date")
                                .unit(Income.Unit.YEARLY)
                                .build()
                        )
                        .build()
                )
            )
        assertThat(employmentDataResponse.code()).isEqualTo(0L)
        assertThat(employmentDataResponse.individualId())
            .isEqualTo("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val employmentDataResponse =
            EmploymentDataResponse.builder()
                .body(
                    EmploymentData.UnionMember0.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .classCode("class_code")
                        .addCustomField(
                            EmploymentData.UnionMember0.CustomField.builder()
                                .name("name")
                                .value("string")
                                .build()
                        )
                        .department(
                            EmploymentData.UnionMember0.Department.builder().name("name").build()
                        )
                        .employment(
                            EmploymentData.UnionMember0.Employment.builder()
                                .subtype(EmploymentData.UnionMember0.Employment.Subtype.FULL_TIME)
                                .type(EmploymentData.UnionMember0.Employment.Type.EMPLOYEE)
                                .build()
                        )
                        .employmentStatus(EmploymentData.UnionMember0.EmploymentStatus.ACTIVE)
                        .endDate("end_date")
                        .firstName("first_name")
                        .isActive(true)
                        .lastName("last_name")
                        .latestRehireDate("latest_rehire_date")
                        .location(
                            Location.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .name("name")
                                .sourceId("source_id")
                                .build()
                        )
                        .manager(
                            EmploymentData.UnionMember0.Manager.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .build()
                        )
                        .middleName("middle_name")
                        .sourceId("source_id")
                        .startDate("start_date")
                        .title("title")
                        .workId("work_id")
                        .income(
                            Income.builder()
                                .amount(0L)
                                .currency("currency")
                                .effectiveDate("effective_date")
                                .unit(Income.Unit.YEARLY)
                                .build()
                        )
                        .addIncomeHistory(
                            Income.builder()
                                .amount(0L)
                                .currency("currency")
                                .effectiveDate("effective_date")
                                .unit(Income.Unit.YEARLY)
                                .build()
                        )
                        .build()
                )
                .code(0L)
                .individualId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                .build()

        val roundtrippedEmploymentDataResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(employmentDataResponse),
                jacksonTypeRef<EmploymentDataResponse>(),
            )

        assertThat(roundtrippedEmploymentDataResponse).isEqualTo(employmentDataResponse)
    }
}
