// File generated from our OpenAPI spec by Stainless.

package com.tryfinch.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.tryfinch.api.core.JsonValue
import com.tryfinch.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class HrisPayStatementRetrieveManyPageResponseTest {

    @Test
    fun create() {
        val hrisPayStatementRetrieveManyPageResponse =
            HrisPayStatementRetrieveManyPageResponse.builder()
                .addResponse(
                    PayStatementResponse.builder()
                        .body(
                            PayStatementResponseBody.UnionMember0.builder()
                                .paging(
                                    PayStatementResponseBody.UnionMember0.Paging.builder()
                                        .offset(0L)
                                        .count(0L)
                                        .build()
                                )
                                .addPayStatement(
                                    PayStatementResponseBody.UnionMember0.PayStatement.builder()
                                        .addEarning(
                                            PayStatementResponseBody.UnionMember0.PayStatement
                                                .Earning
                                                .builder()
                                                .amount(0L)
                                                .currency("currency")
                                                .hours(0.0)
                                                .name("name")
                                                .type(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .Earning
                                                        .Type
                                                        .SALARY
                                                )
                                                .attributes(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .Earning
                                                        .Attributes
                                                        .builder()
                                                        .metadata(
                                                            PayStatementResponseBody.UnionMember0
                                                                .PayStatement
                                                                .Earning
                                                                .Attributes
                                                                .Metadata
                                                                .builder()
                                                                .metadata(
                                                                    PayStatementResponseBody
                                                                        .UnionMember0
                                                                        .PayStatement
                                                                        .Earning
                                                                        .Attributes
                                                                        .Metadata
                                                                        .InnerMetadata
                                                                        .builder()
                                                                        .putAdditionalProperty(
                                                                            "foo",
                                                                            JsonValue.from(
                                                                                mapOf<String, Any>()
                                                                            ),
                                                                        )
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addEmployeeDeduction(
                                            PayStatementResponseBody.UnionMember0.PayStatement
                                                .EmployeeDeduction
                                                .builder()
                                                .amount(0L)
                                                .currency("currency")
                                                .name("name")
                                                .preTax(true)
                                                .type(BenefitType._457)
                                                .attributes(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .EmployeeDeduction
                                                        .Attributes
                                                        .builder()
                                                        .metadata(
                                                            PayStatementResponseBody.UnionMember0
                                                                .PayStatement
                                                                .EmployeeDeduction
                                                                .Attributes
                                                                .Metadata
                                                                .builder()
                                                                .metadata(
                                                                    PayStatementResponseBody
                                                                        .UnionMember0
                                                                        .PayStatement
                                                                        .EmployeeDeduction
                                                                        .Attributes
                                                                        .Metadata
                                                                        .InnerMetadata
                                                                        .builder()
                                                                        .putAdditionalProperty(
                                                                            "foo",
                                                                            JsonValue.from(
                                                                                mapOf<String, Any>()
                                                                            ),
                                                                        )
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addEmployerContribution(
                                            PayStatementResponseBody.UnionMember0.PayStatement
                                                .EmployerContribution
                                                .builder()
                                                .currency("currency")
                                                .name("name")
                                                .type(BenefitType._457)
                                                .amount(0L)
                                                .attributes(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .EmployerContribution
                                                        .Attributes
                                                        .builder()
                                                        .metadata(
                                                            PayStatementResponseBody.UnionMember0
                                                                .PayStatement
                                                                .EmployerContribution
                                                                .Attributes
                                                                .Metadata
                                                                .builder()
                                                                .metadata(
                                                                    PayStatementResponseBody
                                                                        .UnionMember0
                                                                        .PayStatement
                                                                        .EmployerContribution
                                                                        .Attributes
                                                                        .Metadata
                                                                        .InnerMetadata
                                                                        .builder()
                                                                        .putAdditionalProperty(
                                                                            "foo",
                                                                            JsonValue.from(
                                                                                mapOf<String, Any>()
                                                                            ),
                                                                        )
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .grossPay(
                                            Money.builder().amount(0L).currency("currency").build()
                                        )
                                        .individualId("individual_id")
                                        .netPay(
                                            Money.builder().amount(0L).currency("currency").build()
                                        )
                                        .paymentMethod(
                                            PayStatementResponseBody.UnionMember0.PayStatement
                                                .PaymentMethod
                                                .CHECK
                                        )
                                        .addTax(
                                            PayStatementResponseBody.UnionMember0.PayStatement.Tax
                                                .builder()
                                                .currency("currency")
                                                .employer(true)
                                                .name("name")
                                                .type(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .Tax
                                                        .Type
                                                        .STATE
                                                )
                                                .amount(0L)
                                                .attributes(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .Tax
                                                        .Attributes
                                                        .builder()
                                                        .metadata(
                                                            PayStatementResponseBody.UnionMember0
                                                                .PayStatement
                                                                .Tax
                                                                .Attributes
                                                                .Metadata
                                                                .builder()
                                                                .metadata(
                                                                    PayStatementResponseBody
                                                                        .UnionMember0
                                                                        .PayStatement
                                                                        .Tax
                                                                        .Attributes
                                                                        .Metadata
                                                                        .InnerMetadata
                                                                        .builder()
                                                                        .putAdditionalProperty(
                                                                            "foo",
                                                                            JsonValue.from(
                                                                                mapOf<String, Any>()
                                                                            ),
                                                                        )
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .totalHours(0.0)
                                        .type(
                                            PayStatementResponseBody.UnionMember0.PayStatement.Type
                                                .OFF_CYCLE_PAYROLL
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .code(0L)
                        .paymentId("payment_id")
                        .build()
                )
                .build()

        assertThat(hrisPayStatementRetrieveManyPageResponse.responses())
            .containsExactly(
                PayStatementResponse.builder()
                    .body(
                        PayStatementResponseBody.UnionMember0.builder()
                            .paging(
                                PayStatementResponseBody.UnionMember0.Paging.builder()
                                    .offset(0L)
                                    .count(0L)
                                    .build()
                            )
                            .addPayStatement(
                                PayStatementResponseBody.UnionMember0.PayStatement.builder()
                                    .addEarning(
                                        PayStatementResponseBody.UnionMember0.PayStatement.Earning
                                            .builder()
                                            .amount(0L)
                                            .currency("currency")
                                            .hours(0.0)
                                            .name("name")
                                            .type(
                                                PayStatementResponseBody.UnionMember0.PayStatement
                                                    .Earning
                                                    .Type
                                                    .SALARY
                                            )
                                            .attributes(
                                                PayStatementResponseBody.UnionMember0.PayStatement
                                                    .Earning
                                                    .Attributes
                                                    .builder()
                                                    .metadata(
                                                        PayStatementResponseBody.UnionMember0
                                                            .PayStatement
                                                            .Earning
                                                            .Attributes
                                                            .Metadata
                                                            .builder()
                                                            .metadata(
                                                                PayStatementResponseBody
                                                                    .UnionMember0
                                                                    .PayStatement
                                                                    .Earning
                                                                    .Attributes
                                                                    .Metadata
                                                                    .InnerMetadata
                                                                    .builder()
                                                                    .putAdditionalProperty(
                                                                        "foo",
                                                                        JsonValue.from(
                                                                            mapOf<String, Any>()
                                                                        ),
                                                                    )
                                                                    .build()
                                                            )
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .addEmployeeDeduction(
                                        PayStatementResponseBody.UnionMember0.PayStatement
                                            .EmployeeDeduction
                                            .builder()
                                            .amount(0L)
                                            .currency("currency")
                                            .name("name")
                                            .preTax(true)
                                            .type(BenefitType._457)
                                            .attributes(
                                                PayStatementResponseBody.UnionMember0.PayStatement
                                                    .EmployeeDeduction
                                                    .Attributes
                                                    .builder()
                                                    .metadata(
                                                        PayStatementResponseBody.UnionMember0
                                                            .PayStatement
                                                            .EmployeeDeduction
                                                            .Attributes
                                                            .Metadata
                                                            .builder()
                                                            .metadata(
                                                                PayStatementResponseBody
                                                                    .UnionMember0
                                                                    .PayStatement
                                                                    .EmployeeDeduction
                                                                    .Attributes
                                                                    .Metadata
                                                                    .InnerMetadata
                                                                    .builder()
                                                                    .putAdditionalProperty(
                                                                        "foo",
                                                                        JsonValue.from(
                                                                            mapOf<String, Any>()
                                                                        ),
                                                                    )
                                                                    .build()
                                                            )
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .addEmployerContribution(
                                        PayStatementResponseBody.UnionMember0.PayStatement
                                            .EmployerContribution
                                            .builder()
                                            .currency("currency")
                                            .name("name")
                                            .type(BenefitType._457)
                                            .amount(0L)
                                            .attributes(
                                                PayStatementResponseBody.UnionMember0.PayStatement
                                                    .EmployerContribution
                                                    .Attributes
                                                    .builder()
                                                    .metadata(
                                                        PayStatementResponseBody.UnionMember0
                                                            .PayStatement
                                                            .EmployerContribution
                                                            .Attributes
                                                            .Metadata
                                                            .builder()
                                                            .metadata(
                                                                PayStatementResponseBody
                                                                    .UnionMember0
                                                                    .PayStatement
                                                                    .EmployerContribution
                                                                    .Attributes
                                                                    .Metadata
                                                                    .InnerMetadata
                                                                    .builder()
                                                                    .putAdditionalProperty(
                                                                        "foo",
                                                                        JsonValue.from(
                                                                            mapOf<String, Any>()
                                                                        ),
                                                                    )
                                                                    .build()
                                                            )
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .grossPay(
                                        Money.builder().amount(0L).currency("currency").build()
                                    )
                                    .individualId("individual_id")
                                    .netPay(Money.builder().amount(0L).currency("currency").build())
                                    .paymentMethod(
                                        PayStatementResponseBody.UnionMember0.PayStatement
                                            .PaymentMethod
                                            .CHECK
                                    )
                                    .addTax(
                                        PayStatementResponseBody.UnionMember0.PayStatement.Tax
                                            .builder()
                                            .currency("currency")
                                            .employer(true)
                                            .name("name")
                                            .type(
                                                PayStatementResponseBody.UnionMember0.PayStatement
                                                    .Tax
                                                    .Type
                                                    .STATE
                                            )
                                            .amount(0L)
                                            .attributes(
                                                PayStatementResponseBody.UnionMember0.PayStatement
                                                    .Tax
                                                    .Attributes
                                                    .builder()
                                                    .metadata(
                                                        PayStatementResponseBody.UnionMember0
                                                            .PayStatement
                                                            .Tax
                                                            .Attributes
                                                            .Metadata
                                                            .builder()
                                                            .metadata(
                                                                PayStatementResponseBody
                                                                    .UnionMember0
                                                                    .PayStatement
                                                                    .Tax
                                                                    .Attributes
                                                                    .Metadata
                                                                    .InnerMetadata
                                                                    .builder()
                                                                    .putAdditionalProperty(
                                                                        "foo",
                                                                        JsonValue.from(
                                                                            mapOf<String, Any>()
                                                                        ),
                                                                    )
                                                                    .build()
                                                            )
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .totalHours(0.0)
                                    .type(
                                        PayStatementResponseBody.UnionMember0.PayStatement.Type
                                            .OFF_CYCLE_PAYROLL
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .code(0L)
                    .paymentId("payment_id")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val hrisPayStatementRetrieveManyPageResponse =
            HrisPayStatementRetrieveManyPageResponse.builder()
                .addResponse(
                    PayStatementResponse.builder()
                        .body(
                            PayStatementResponseBody.UnionMember0.builder()
                                .paging(
                                    PayStatementResponseBody.UnionMember0.Paging.builder()
                                        .offset(0L)
                                        .count(0L)
                                        .build()
                                )
                                .addPayStatement(
                                    PayStatementResponseBody.UnionMember0.PayStatement.builder()
                                        .addEarning(
                                            PayStatementResponseBody.UnionMember0.PayStatement
                                                .Earning
                                                .builder()
                                                .amount(0L)
                                                .currency("currency")
                                                .hours(0.0)
                                                .name("name")
                                                .type(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .Earning
                                                        .Type
                                                        .SALARY
                                                )
                                                .attributes(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .Earning
                                                        .Attributes
                                                        .builder()
                                                        .metadata(
                                                            PayStatementResponseBody.UnionMember0
                                                                .PayStatement
                                                                .Earning
                                                                .Attributes
                                                                .Metadata
                                                                .builder()
                                                                .metadata(
                                                                    PayStatementResponseBody
                                                                        .UnionMember0
                                                                        .PayStatement
                                                                        .Earning
                                                                        .Attributes
                                                                        .Metadata
                                                                        .InnerMetadata
                                                                        .builder()
                                                                        .putAdditionalProperty(
                                                                            "foo",
                                                                            JsonValue.from(
                                                                                mapOf<String, Any>()
                                                                            ),
                                                                        )
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addEmployeeDeduction(
                                            PayStatementResponseBody.UnionMember0.PayStatement
                                                .EmployeeDeduction
                                                .builder()
                                                .amount(0L)
                                                .currency("currency")
                                                .name("name")
                                                .preTax(true)
                                                .type(BenefitType._457)
                                                .attributes(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .EmployeeDeduction
                                                        .Attributes
                                                        .builder()
                                                        .metadata(
                                                            PayStatementResponseBody.UnionMember0
                                                                .PayStatement
                                                                .EmployeeDeduction
                                                                .Attributes
                                                                .Metadata
                                                                .builder()
                                                                .metadata(
                                                                    PayStatementResponseBody
                                                                        .UnionMember0
                                                                        .PayStatement
                                                                        .EmployeeDeduction
                                                                        .Attributes
                                                                        .Metadata
                                                                        .InnerMetadata
                                                                        .builder()
                                                                        .putAdditionalProperty(
                                                                            "foo",
                                                                            JsonValue.from(
                                                                                mapOf<String, Any>()
                                                                            ),
                                                                        )
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .addEmployerContribution(
                                            PayStatementResponseBody.UnionMember0.PayStatement
                                                .EmployerContribution
                                                .builder()
                                                .currency("currency")
                                                .name("name")
                                                .type(BenefitType._457)
                                                .amount(0L)
                                                .attributes(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .EmployerContribution
                                                        .Attributes
                                                        .builder()
                                                        .metadata(
                                                            PayStatementResponseBody.UnionMember0
                                                                .PayStatement
                                                                .EmployerContribution
                                                                .Attributes
                                                                .Metadata
                                                                .builder()
                                                                .metadata(
                                                                    PayStatementResponseBody
                                                                        .UnionMember0
                                                                        .PayStatement
                                                                        .EmployerContribution
                                                                        .Attributes
                                                                        .Metadata
                                                                        .InnerMetadata
                                                                        .builder()
                                                                        .putAdditionalProperty(
                                                                            "foo",
                                                                            JsonValue.from(
                                                                                mapOf<String, Any>()
                                                                            ),
                                                                        )
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .grossPay(
                                            Money.builder().amount(0L).currency("currency").build()
                                        )
                                        .individualId("individual_id")
                                        .netPay(
                                            Money.builder().amount(0L).currency("currency").build()
                                        )
                                        .paymentMethod(
                                            PayStatementResponseBody.UnionMember0.PayStatement
                                                .PaymentMethod
                                                .CHECK
                                        )
                                        .addTax(
                                            PayStatementResponseBody.UnionMember0.PayStatement.Tax
                                                .builder()
                                                .currency("currency")
                                                .employer(true)
                                                .name("name")
                                                .type(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .Tax
                                                        .Type
                                                        .STATE
                                                )
                                                .amount(0L)
                                                .attributes(
                                                    PayStatementResponseBody.UnionMember0
                                                        .PayStatement
                                                        .Tax
                                                        .Attributes
                                                        .builder()
                                                        .metadata(
                                                            PayStatementResponseBody.UnionMember0
                                                                .PayStatement
                                                                .Tax
                                                                .Attributes
                                                                .Metadata
                                                                .builder()
                                                                .metadata(
                                                                    PayStatementResponseBody
                                                                        .UnionMember0
                                                                        .PayStatement
                                                                        .Tax
                                                                        .Attributes
                                                                        .Metadata
                                                                        .InnerMetadata
                                                                        .builder()
                                                                        .putAdditionalProperty(
                                                                            "foo",
                                                                            JsonValue.from(
                                                                                mapOf<String, Any>()
                                                                            ),
                                                                        )
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .totalHours(0.0)
                                        .type(
                                            PayStatementResponseBody.UnionMember0.PayStatement.Type
                                                .OFF_CYCLE_PAYROLL
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .code(0L)
                        .paymentId("payment_id")
                        .build()
                )
                .build()

        val roundtrippedHrisPayStatementRetrieveManyPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(hrisPayStatementRetrieveManyPageResponse),
                jacksonTypeRef<HrisPayStatementRetrieveManyPageResponse>(),
            )

        assertThat(roundtrippedHrisPayStatementRetrieveManyPageResponse)
            .isEqualTo(hrisPayStatementRetrieveManyPageResponse)
    }
}
