// File generated from our OpenAPI spec by Stainless.

package com.tryfinch.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.tryfinch.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class HrisEmploymentRetrieveManyPageResponseTest {

    @Test
    fun create() {
        val hrisEmploymentRetrieveManyPageResponse =
            HrisEmploymentRetrieveManyPageResponse.builder()
                .addResponse(
                    EmploymentDataResponse.builder()
                        .body(
                            EmploymentData.UnionMember0.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .classCode("class_code")
                                .department(
                                    EmploymentData.UnionMember0.Department.builder()
                                        .name("name")
                                        .build()
                                )
                                .employment(
                                    EmploymentData.UnionMember0.Employment.builder()
                                        .subtype(
                                            EmploymentData.UnionMember0.Employment.Subtype.FULL_TIME
                                        )
                                        .type(EmploymentData.UnionMember0.Employment.Type.EMPLOYEE)
                                        .build()
                                )
                                .employmentStatus(
                                    EmploymentData.UnionMember0.EmploymentStatus.ACTIVE
                                )
                                .endDate("end_date")
                                .firstName("first_name")
                                .isActive(true)
                                .lastName("last_name")
                                .latestRehireDate("latest_rehire_date")
                                .location(
                                    Location.builder()
                                        .city("city")
                                        .country("country")
                                        .line1("line1")
                                        .line2("line2")
                                        .postalCode("postal_code")
                                        .state("state")
                                        .name("name")
                                        .sourceId("source_id")
                                        .build()
                                )
                                .manager(
                                    EmploymentData.UnionMember0.Manager.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .middleName("middle_name")
                                .startDate("start_date")
                                .title("title")
                                .addCustomField(
                                    EmploymentData.UnionMember0.CustomField.builder()
                                        .name("name")
                                        .value("string")
                                        .build()
                                )
                                .income(
                                    Income.builder()
                                        .amount(0L)
                                        .currency("currency")
                                        .effectiveDate("effective_date")
                                        .unit(Income.Unit.YEARLY)
                                        .build()
                                )
                                .addIncomeHistory(
                                    Income.builder()
                                        .amount(0L)
                                        .currency("currency")
                                        .effectiveDate("effective_date")
                                        .unit(Income.Unit.YEARLY)
                                        .build()
                                )
                                .sourceId("source_id")
                                .workId("work_id")
                                .build()
                        )
                        .code(0L)
                        .individualId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .build()

        assertThat(hrisEmploymentRetrieveManyPageResponse.responses())
            .containsExactly(
                EmploymentDataResponse.builder()
                    .body(
                        EmploymentData.UnionMember0.builder()
                            .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                            .classCode("class_code")
                            .department(
                                EmploymentData.UnionMember0.Department.builder()
                                    .name("name")
                                    .build()
                            )
                            .employment(
                                EmploymentData.UnionMember0.Employment.builder()
                                    .subtype(
                                        EmploymentData.UnionMember0.Employment.Subtype.FULL_TIME
                                    )
                                    .type(EmploymentData.UnionMember0.Employment.Type.EMPLOYEE)
                                    .build()
                            )
                            .employmentStatus(EmploymentData.UnionMember0.EmploymentStatus.ACTIVE)
                            .endDate("end_date")
                            .firstName("first_name")
                            .isActive(true)
                            .lastName("last_name")
                            .latestRehireDate("latest_rehire_date")
                            .location(
                                Location.builder()
                                    .city("city")
                                    .country("country")
                                    .line1("line1")
                                    .line2("line2")
                                    .postalCode("postal_code")
                                    .state("state")
                                    .name("name")
                                    .sourceId("source_id")
                                    .build()
                            )
                            .manager(
                                EmploymentData.UnionMember0.Manager.builder()
                                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                    .build()
                            )
                            .middleName("middle_name")
                            .startDate("start_date")
                            .title("title")
                            .addCustomField(
                                EmploymentData.UnionMember0.CustomField.builder()
                                    .name("name")
                                    .value("string")
                                    .build()
                            )
                            .income(
                                Income.builder()
                                    .amount(0L)
                                    .currency("currency")
                                    .effectiveDate("effective_date")
                                    .unit(Income.Unit.YEARLY)
                                    .build()
                            )
                            .addIncomeHistory(
                                Income.builder()
                                    .amount(0L)
                                    .currency("currency")
                                    .effectiveDate("effective_date")
                                    .unit(Income.Unit.YEARLY)
                                    .build()
                            )
                            .sourceId("source_id")
                            .workId("work_id")
                            .build()
                    )
                    .code(0L)
                    .individualId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val hrisEmploymentRetrieveManyPageResponse =
            HrisEmploymentRetrieveManyPageResponse.builder()
                .addResponse(
                    EmploymentDataResponse.builder()
                        .body(
                            EmploymentData.UnionMember0.builder()
                                .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                .classCode("class_code")
                                .department(
                                    EmploymentData.UnionMember0.Department.builder()
                                        .name("name")
                                        .build()
                                )
                                .employment(
                                    EmploymentData.UnionMember0.Employment.builder()
                                        .subtype(
                                            EmploymentData.UnionMember0.Employment.Subtype.FULL_TIME
                                        )
                                        .type(EmploymentData.UnionMember0.Employment.Type.EMPLOYEE)
                                        .build()
                                )
                                .employmentStatus(
                                    EmploymentData.UnionMember0.EmploymentStatus.ACTIVE
                                )
                                .endDate("end_date")
                                .firstName("first_name")
                                .isActive(true)
                                .lastName("last_name")
                                .latestRehireDate("latest_rehire_date")
                                .location(
                                    Location.builder()
                                        .city("city")
                                        .country("country")
                                        .line1("line1")
                                        .line2("line2")
                                        .postalCode("postal_code")
                                        .state("state")
                                        .name("name")
                                        .sourceId("source_id")
                                        .build()
                                )
                                .manager(
                                    EmploymentData.UnionMember0.Manager.builder()
                                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                                        .build()
                                )
                                .middleName("middle_name")
                                .startDate("start_date")
                                .title("title")
                                .addCustomField(
                                    EmploymentData.UnionMember0.CustomField.builder()
                                        .name("name")
                                        .value("string")
                                        .build()
                                )
                                .income(
                                    Income.builder()
                                        .amount(0L)
                                        .currency("currency")
                                        .effectiveDate("effective_date")
                                        .unit(Income.Unit.YEARLY)
                                        .build()
                                )
                                .addIncomeHistory(
                                    Income.builder()
                                        .amount(0L)
                                        .currency("currency")
                                        .effectiveDate("effective_date")
                                        .unit(Income.Unit.YEARLY)
                                        .build()
                                )
                                .sourceId("source_id")
                                .workId("work_id")
                                .build()
                        )
                        .code(0L)
                        .individualId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .build()

        val roundtrippedHrisEmploymentRetrieveManyPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(hrisEmploymentRetrieveManyPageResponse),
                jacksonTypeRef<HrisEmploymentRetrieveManyPageResponse>(),
            )

        assertThat(roundtrippedHrisEmploymentRetrieveManyPageResponse)
            .isEqualTo(hrisEmploymentRetrieveManyPageResponse)
    }
}
