// File generated from our OpenAPI spec by Stainless.

package com.tryfinch.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.tryfinch.api.core.JsonValue
import com.tryfinch.api.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ProviderListResponseTest {

    @Test
    fun create() {
        val providerListResponse =
            ProviderListResponse.builder()
                .id("id")
                .displayName("display_name")
                .addProduct("string")
                .addAuthenticationMethod(
                    ProviderListResponse.AuthenticationMethod.builder()
                        .type(ProviderListResponse.AuthenticationMethod.Type.ASSISTED)
                        .benefitsSupport(
                            ProviderListResponse.AuthenticationMethod.BenefitsSupport.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .supportedFields(
                            ProviderListResponse.AuthenticationMethod.SupportedFields.builder()
                                .company(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedCompanyFields
                                        .builder()
                                        .id(true)
                                        .accounts(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedCompanyFields
                                                .Accounts
                                                .builder()
                                                .accountName(true)
                                                .accountNumber(true)
                                                .accountType(true)
                                                .institutionName(true)
                                                .routingNumber(true)
                                                .build()
                                        )
                                        .departments(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedCompanyFields
                                                .Departments
                                                .builder()
                                                .name(true)
                                                .parent(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedCompanyFields
                                                        .Departments
                                                        .Parent
                                                        .builder()
                                                        .name(true)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .ein(true)
                                        .entity(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedCompanyFields
                                                .Entity
                                                .builder()
                                                .subtype(true)
                                                .type(true)
                                                .build()
                                        )
                                        .legalName(true)
                                        .locations(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedCompanyFields
                                                .Locations
                                                .builder()
                                                .city(true)
                                                .country(true)
                                                .line1(true)
                                                .line2(true)
                                                .postalCode(true)
                                                .state(true)
                                                .build()
                                        )
                                        .primaryEmail(true)
                                        .primaryPhoneNumber(true)
                                        .build()
                                )
                                .directory(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedDirectoryFields
                                        .builder()
                                        .individuals(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedDirectoryFields
                                                .Individuals
                                                .builder()
                                                .id(true)
                                                .department(true)
                                                .firstName(true)
                                                .isActive(true)
                                                .lastName(true)
                                                .manager(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedDirectoryFields
                                                        .Individuals
                                                        .Manager
                                                        .builder()
                                                        .id(true)
                                                        .build()
                                                )
                                                .middleName(true)
                                                .build()
                                        )
                                        .paging(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedDirectoryFields
                                                .Paging
                                                .builder()
                                                .count(true)
                                                .offset(true)
                                                .build()
                                        )
                                        .build()
                                )
                                .employment(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedEmploymentFields
                                        .builder()
                                        .id(true)
                                        .classCode(true)
                                        .customFields(true)
                                        .department(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedEmploymentFields
                                                .Department
                                                .builder()
                                                .name(true)
                                                .build()
                                        )
                                        .employment(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedEmploymentFields
                                                .Employment
                                                .builder()
                                                .subtype(true)
                                                .type(true)
                                                .build()
                                        )
                                        .employmentStatus(true)
                                        .endDate(true)
                                        .firstName(true)
                                        .income(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedEmploymentFields
                                                .Income
                                                .builder()
                                                .amount(true)
                                                .currency(true)
                                                .unit(true)
                                                .build()
                                        )
                                        .incomeHistory(true)
                                        .isActive(true)
                                        .lastName(true)
                                        .location(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedEmploymentFields
                                                .Location
                                                .builder()
                                                .city(true)
                                                .country(true)
                                                .line1(true)
                                                .line2(true)
                                                .postalCode(true)
                                                .state(true)
                                                .build()
                                        )
                                        .manager(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedEmploymentFields
                                                .Manager
                                                .builder()
                                                .id(true)
                                                .build()
                                        )
                                        .middleName(true)
                                        .startDate(true)
                                        .title(true)
                                        .build()
                                )
                                .individual(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedIndividualFields
                                        .builder()
                                        .id(true)
                                        .dob(true)
                                        .emails(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedIndividualFields
                                                .Emails
                                                .builder()
                                                .data(true)
                                                .type(true)
                                                .build()
                                        )
                                        .encryptedSsn(true)
                                        .ethnicity(true)
                                        .firstName(true)
                                        .gender(true)
                                        .lastName(true)
                                        .middleName(true)
                                        .phoneNumbers(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedIndividualFields
                                                .PhoneNumbers
                                                .builder()
                                                .data(true)
                                                .type(true)
                                                .build()
                                        )
                                        .preferredName(true)
                                        .residence(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedIndividualFields
                                                .Residence
                                                .builder()
                                                .city(true)
                                                .country(true)
                                                .line1(true)
                                                .line2(true)
                                                .postalCode(true)
                                                .state(true)
                                                .build()
                                        )
                                        .ssn(true)
                                        .build()
                                )
                                .payGroup(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPayGroupFields
                                        .builder()
                                        .id(true)
                                        .individualIds(true)
                                        .name(true)
                                        .payFrequencies(true)
                                        .build()
                                )
                                .payStatement(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPayStatementFields
                                        .builder()
                                        .paging(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPayStatementFields
                                                .Paging
                                                .builder()
                                                .count(true)
                                                .offset(true)
                                                .build()
                                        )
                                        .payStatements(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPayStatementFields
                                                .PayStatements
                                                .builder()
                                                .earnings(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPayStatementFields
                                                        .PayStatements
                                                        .Earnings
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .name(true)
                                                        .type(true)
                                                        .build()
                                                )
                                                .employeeDeductions(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPayStatementFields
                                                        .PayStatements
                                                        .EmployeeDeductions
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .name(true)
                                                        .preTax(true)
                                                        .type(true)
                                                        .build()
                                                )
                                                .employerContributions(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPayStatementFields
                                                        .PayStatements
                                                        .EmployerContributions
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .name(true)
                                                        .build()
                                                )
                                                .grossPay(true)
                                                .individualId(true)
                                                .netPay(true)
                                                .paymentMethod(true)
                                                .taxes(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPayStatementFields
                                                        .PayStatements
                                                        .Taxes
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .employer(true)
                                                        .name(true)
                                                        .type(true)
                                                        .build()
                                                )
                                                .totalHours(true)
                                                .type(true)
                                                .build()
                                        )
                                        .build()
                                )
                                .payment(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPaymentFields
                                        .builder()
                                        .id(true)
                                        .companyDebit(true)
                                        .debitDate(true)
                                        .employeeTaxes(true)
                                        .employerTaxes(true)
                                        .grossPay(true)
                                        .individualIds(true)
                                        .netPay(true)
                                        .payDate(true)
                                        .payFrequencies(true)
                                        .payGroupIds(true)
                                        .payPeriod(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPaymentFields
                                                .PayPeriod
                                                .builder()
                                                .endDate(true)
                                                .startDate(true)
                                                .build()
                                        )
                                        .build()
                                )
                                .planDependents(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPlanDependentFields
                                        .builder()
                                        .coverage(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPlanDependentFields
                                                .Coverage
                                                .builder()
                                                .enrollments(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPlanDependentFields
                                                        .Coverage
                                                        .Enrollments
                                                        .builder()
                                                        .id(true)
                                                        .type(true)
                                                        .build()
                                                )
                                                .individualId(true)
                                                .relationshipToIndividual(true)
                                                .build()
                                        )
                                        .dateOfBirth(true)
                                        .dependentId(true)
                                        .firstName(true)
                                        .gender(true)
                                        .lastName(true)
                                        .middleName(true)
                                        .ssn(true)
                                        .build()
                                )
                                .planEnrollments(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPlanEnrollmentFields
                                        .builder()
                                        .id(true)
                                        .contributions(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPlanEnrollmentFields
                                                .Contributions
                                                .builder()
                                                .employeeContribution(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPlanEnrollmentFields
                                                        .Contributions
                                                        .EmployeeContribution
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .build()
                                                )
                                                .employerContribution(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPlanEnrollmentFields
                                                        .Contributions
                                                        .EmployerContribution
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .build()
                                                )
                                                .frequency(true)
                                                .build()
                                        )
                                        .coverageEndDate(true)
                                        .coverageStartDate(true)
                                        .coverageTier(true)
                                        .dependentIds(true)
                                        .individualId(true)
                                        .planId(true)
                                        .status(true)
                                        .build()
                                )
                                .plans(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPlanFields
                                        .builder()
                                        .id(true)
                                        .carrier(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPlanFields
                                                .Carrier
                                                .builder()
                                                .id(true)
                                                .name(true)
                                                .build()
                                        )
                                        .coverageTiers(true)
                                        .deductionCodes(true)
                                        .description(true)
                                        .endDate(true)
                                        .name(true)
                                        .networkType(true)
                                        .startDate(true)
                                        .type(true)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .beta(true)
                .icon("icon")
                .logo("logo")
                .manual(true)
                .mfaRequired(true)
                .primaryColor("primary_color")
                .build()

        assertThat(providerListResponse.id()).isEqualTo("id")
        assertThat(providerListResponse.displayName()).isEqualTo("display_name")
        assertThat(providerListResponse.products()).containsExactly("string")
        assertThat(providerListResponse.authenticationMethods().getOrNull())
            .containsExactly(
                ProviderListResponse.AuthenticationMethod.builder()
                    .type(ProviderListResponse.AuthenticationMethod.Type.ASSISTED)
                    .benefitsSupport(
                        ProviderListResponse.AuthenticationMethod.BenefitsSupport.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .supportedFields(
                        ProviderListResponse.AuthenticationMethod.SupportedFields.builder()
                            .company(
                                ProviderListResponse.AuthenticationMethod.SupportedFields
                                    .SupportedCompanyFields
                                    .builder()
                                    .id(true)
                                    .accounts(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedCompanyFields
                                            .Accounts
                                            .builder()
                                            .accountName(true)
                                            .accountNumber(true)
                                            .accountType(true)
                                            .institutionName(true)
                                            .routingNumber(true)
                                            .build()
                                    )
                                    .departments(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedCompanyFields
                                            .Departments
                                            .builder()
                                            .name(true)
                                            .parent(
                                                ProviderListResponse.AuthenticationMethod
                                                    .SupportedFields
                                                    .SupportedCompanyFields
                                                    .Departments
                                                    .Parent
                                                    .builder()
                                                    .name(true)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .ein(true)
                                    .entity(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedCompanyFields
                                            .Entity
                                            .builder()
                                            .subtype(true)
                                            .type(true)
                                            .build()
                                    )
                                    .legalName(true)
                                    .locations(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedCompanyFields
                                            .Locations
                                            .builder()
                                            .city(true)
                                            .country(true)
                                            .line1(true)
                                            .line2(true)
                                            .postalCode(true)
                                            .state(true)
                                            .build()
                                    )
                                    .primaryEmail(true)
                                    .primaryPhoneNumber(true)
                                    .build()
                            )
                            .directory(
                                ProviderListResponse.AuthenticationMethod.SupportedFields
                                    .SupportedDirectoryFields
                                    .builder()
                                    .individuals(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedDirectoryFields
                                            .Individuals
                                            .builder()
                                            .id(true)
                                            .department(true)
                                            .firstName(true)
                                            .isActive(true)
                                            .lastName(true)
                                            .manager(
                                                ProviderListResponse.AuthenticationMethod
                                                    .SupportedFields
                                                    .SupportedDirectoryFields
                                                    .Individuals
                                                    .Manager
                                                    .builder()
                                                    .id(true)
                                                    .build()
                                            )
                                            .middleName(true)
                                            .build()
                                    )
                                    .paging(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedDirectoryFields
                                            .Paging
                                            .builder()
                                            .count(true)
                                            .offset(true)
                                            .build()
                                    )
                                    .build()
                            )
                            .employment(
                                ProviderListResponse.AuthenticationMethod.SupportedFields
                                    .SupportedEmploymentFields
                                    .builder()
                                    .id(true)
                                    .classCode(true)
                                    .customFields(true)
                                    .department(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedEmploymentFields
                                            .Department
                                            .builder()
                                            .name(true)
                                            .build()
                                    )
                                    .employment(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedEmploymentFields
                                            .Employment
                                            .builder()
                                            .subtype(true)
                                            .type(true)
                                            .build()
                                    )
                                    .employmentStatus(true)
                                    .endDate(true)
                                    .firstName(true)
                                    .income(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedEmploymentFields
                                            .Income
                                            .builder()
                                            .amount(true)
                                            .currency(true)
                                            .unit(true)
                                            .build()
                                    )
                                    .incomeHistory(true)
                                    .isActive(true)
                                    .lastName(true)
                                    .location(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedEmploymentFields
                                            .Location
                                            .builder()
                                            .city(true)
                                            .country(true)
                                            .line1(true)
                                            .line2(true)
                                            .postalCode(true)
                                            .state(true)
                                            .build()
                                    )
                                    .manager(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedEmploymentFields
                                            .Manager
                                            .builder()
                                            .id(true)
                                            .build()
                                    )
                                    .middleName(true)
                                    .startDate(true)
                                    .title(true)
                                    .build()
                            )
                            .individual(
                                ProviderListResponse.AuthenticationMethod.SupportedFields
                                    .SupportedIndividualFields
                                    .builder()
                                    .id(true)
                                    .dob(true)
                                    .emails(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedIndividualFields
                                            .Emails
                                            .builder()
                                            .data(true)
                                            .type(true)
                                            .build()
                                    )
                                    .encryptedSsn(true)
                                    .ethnicity(true)
                                    .firstName(true)
                                    .gender(true)
                                    .lastName(true)
                                    .middleName(true)
                                    .phoneNumbers(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedIndividualFields
                                            .PhoneNumbers
                                            .builder()
                                            .data(true)
                                            .type(true)
                                            .build()
                                    )
                                    .preferredName(true)
                                    .residence(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedIndividualFields
                                            .Residence
                                            .builder()
                                            .city(true)
                                            .country(true)
                                            .line1(true)
                                            .line2(true)
                                            .postalCode(true)
                                            .state(true)
                                            .build()
                                    )
                                    .ssn(true)
                                    .build()
                            )
                            .payGroup(
                                ProviderListResponse.AuthenticationMethod.SupportedFields
                                    .SupportedPayGroupFields
                                    .builder()
                                    .id(true)
                                    .individualIds(true)
                                    .name(true)
                                    .payFrequencies(true)
                                    .build()
                            )
                            .payStatement(
                                ProviderListResponse.AuthenticationMethod.SupportedFields
                                    .SupportedPayStatementFields
                                    .builder()
                                    .paging(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedPayStatementFields
                                            .Paging
                                            .builder()
                                            .count(true)
                                            .offset(true)
                                            .build()
                                    )
                                    .payStatements(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedPayStatementFields
                                            .PayStatements
                                            .builder()
                                            .earnings(
                                                ProviderListResponse.AuthenticationMethod
                                                    .SupportedFields
                                                    .SupportedPayStatementFields
                                                    .PayStatements
                                                    .Earnings
                                                    .builder()
                                                    .amount(true)
                                                    .currency(true)
                                                    .name(true)
                                                    .type(true)
                                                    .build()
                                            )
                                            .employeeDeductions(
                                                ProviderListResponse.AuthenticationMethod
                                                    .SupportedFields
                                                    .SupportedPayStatementFields
                                                    .PayStatements
                                                    .EmployeeDeductions
                                                    .builder()
                                                    .amount(true)
                                                    .currency(true)
                                                    .name(true)
                                                    .preTax(true)
                                                    .type(true)
                                                    .build()
                                            )
                                            .employerContributions(
                                                ProviderListResponse.AuthenticationMethod
                                                    .SupportedFields
                                                    .SupportedPayStatementFields
                                                    .PayStatements
                                                    .EmployerContributions
                                                    .builder()
                                                    .amount(true)
                                                    .currency(true)
                                                    .name(true)
                                                    .build()
                                            )
                                            .grossPay(true)
                                            .individualId(true)
                                            .netPay(true)
                                            .paymentMethod(true)
                                            .taxes(
                                                ProviderListResponse.AuthenticationMethod
                                                    .SupportedFields
                                                    .SupportedPayStatementFields
                                                    .PayStatements
                                                    .Taxes
                                                    .builder()
                                                    .amount(true)
                                                    .currency(true)
                                                    .employer(true)
                                                    .name(true)
                                                    .type(true)
                                                    .build()
                                            )
                                            .totalHours(true)
                                            .type(true)
                                            .build()
                                    )
                                    .build()
                            )
                            .payment(
                                ProviderListResponse.AuthenticationMethod.SupportedFields
                                    .SupportedPaymentFields
                                    .builder()
                                    .id(true)
                                    .companyDebit(true)
                                    .debitDate(true)
                                    .employeeTaxes(true)
                                    .employerTaxes(true)
                                    .grossPay(true)
                                    .individualIds(true)
                                    .netPay(true)
                                    .payDate(true)
                                    .payFrequencies(true)
                                    .payGroupIds(true)
                                    .payPeriod(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedPaymentFields
                                            .PayPeriod
                                            .builder()
                                            .endDate(true)
                                            .startDate(true)
                                            .build()
                                    )
                                    .build()
                            )
                            .planDependents(
                                ProviderListResponse.AuthenticationMethod.SupportedFields
                                    .SupportedPlanDependentFields
                                    .builder()
                                    .coverage(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedPlanDependentFields
                                            .Coverage
                                            .builder()
                                            .enrollments(
                                                ProviderListResponse.AuthenticationMethod
                                                    .SupportedFields
                                                    .SupportedPlanDependentFields
                                                    .Coverage
                                                    .Enrollments
                                                    .builder()
                                                    .id(true)
                                                    .type(true)
                                                    .build()
                                            )
                                            .individualId(true)
                                            .relationshipToIndividual(true)
                                            .build()
                                    )
                                    .dateOfBirth(true)
                                    .dependentId(true)
                                    .firstName(true)
                                    .gender(true)
                                    .lastName(true)
                                    .middleName(true)
                                    .ssn(true)
                                    .build()
                            )
                            .planEnrollments(
                                ProviderListResponse.AuthenticationMethod.SupportedFields
                                    .SupportedPlanEnrollmentFields
                                    .builder()
                                    .id(true)
                                    .contributions(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedPlanEnrollmentFields
                                            .Contributions
                                            .builder()
                                            .employeeContribution(
                                                ProviderListResponse.AuthenticationMethod
                                                    .SupportedFields
                                                    .SupportedPlanEnrollmentFields
                                                    .Contributions
                                                    .EmployeeContribution
                                                    .builder()
                                                    .amount(true)
                                                    .currency(true)
                                                    .build()
                                            )
                                            .employerContribution(
                                                ProviderListResponse.AuthenticationMethod
                                                    .SupportedFields
                                                    .SupportedPlanEnrollmentFields
                                                    .Contributions
                                                    .EmployerContribution
                                                    .builder()
                                                    .amount(true)
                                                    .currency(true)
                                                    .build()
                                            )
                                            .frequency(true)
                                            .build()
                                    )
                                    .coverageEndDate(true)
                                    .coverageStartDate(true)
                                    .coverageTier(true)
                                    .dependentIds(true)
                                    .individualId(true)
                                    .planId(true)
                                    .status(true)
                                    .build()
                            )
                            .plans(
                                ProviderListResponse.AuthenticationMethod.SupportedFields
                                    .SupportedPlanFields
                                    .builder()
                                    .id(true)
                                    .carrier(
                                        ProviderListResponse.AuthenticationMethod.SupportedFields
                                            .SupportedPlanFields
                                            .Carrier
                                            .builder()
                                            .id(true)
                                            .name(true)
                                            .build()
                                    )
                                    .coverageTiers(true)
                                    .deductionCodes(true)
                                    .description(true)
                                    .endDate(true)
                                    .name(true)
                                    .networkType(true)
                                    .startDate(true)
                                    .type(true)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(providerListResponse.beta()).contains(true)
        assertThat(providerListResponse.icon()).contains("icon")
        assertThat(providerListResponse.logo()).contains("logo")
        assertThat(providerListResponse.manual()).contains(true)
        assertThat(providerListResponse.mfaRequired()).contains(true)
        assertThat(providerListResponse.primaryColor()).contains("primary_color")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val providerListResponse =
            ProviderListResponse.builder()
                .id("id")
                .displayName("display_name")
                .addProduct("string")
                .addAuthenticationMethod(
                    ProviderListResponse.AuthenticationMethod.builder()
                        .type(ProviderListResponse.AuthenticationMethod.Type.ASSISTED)
                        .benefitsSupport(
                            ProviderListResponse.AuthenticationMethod.BenefitsSupport.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .supportedFields(
                            ProviderListResponse.AuthenticationMethod.SupportedFields.builder()
                                .company(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedCompanyFields
                                        .builder()
                                        .id(true)
                                        .accounts(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedCompanyFields
                                                .Accounts
                                                .builder()
                                                .accountName(true)
                                                .accountNumber(true)
                                                .accountType(true)
                                                .institutionName(true)
                                                .routingNumber(true)
                                                .build()
                                        )
                                        .departments(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedCompanyFields
                                                .Departments
                                                .builder()
                                                .name(true)
                                                .parent(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedCompanyFields
                                                        .Departments
                                                        .Parent
                                                        .builder()
                                                        .name(true)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .ein(true)
                                        .entity(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedCompanyFields
                                                .Entity
                                                .builder()
                                                .subtype(true)
                                                .type(true)
                                                .build()
                                        )
                                        .legalName(true)
                                        .locations(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedCompanyFields
                                                .Locations
                                                .builder()
                                                .city(true)
                                                .country(true)
                                                .line1(true)
                                                .line2(true)
                                                .postalCode(true)
                                                .state(true)
                                                .build()
                                        )
                                        .primaryEmail(true)
                                        .primaryPhoneNumber(true)
                                        .build()
                                )
                                .directory(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedDirectoryFields
                                        .builder()
                                        .individuals(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedDirectoryFields
                                                .Individuals
                                                .builder()
                                                .id(true)
                                                .department(true)
                                                .firstName(true)
                                                .isActive(true)
                                                .lastName(true)
                                                .manager(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedDirectoryFields
                                                        .Individuals
                                                        .Manager
                                                        .builder()
                                                        .id(true)
                                                        .build()
                                                )
                                                .middleName(true)
                                                .build()
                                        )
                                        .paging(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedDirectoryFields
                                                .Paging
                                                .builder()
                                                .count(true)
                                                .offset(true)
                                                .build()
                                        )
                                        .build()
                                )
                                .employment(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedEmploymentFields
                                        .builder()
                                        .id(true)
                                        .classCode(true)
                                        .customFields(true)
                                        .department(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedEmploymentFields
                                                .Department
                                                .builder()
                                                .name(true)
                                                .build()
                                        )
                                        .employment(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedEmploymentFields
                                                .Employment
                                                .builder()
                                                .subtype(true)
                                                .type(true)
                                                .build()
                                        )
                                        .employmentStatus(true)
                                        .endDate(true)
                                        .firstName(true)
                                        .income(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedEmploymentFields
                                                .Income
                                                .builder()
                                                .amount(true)
                                                .currency(true)
                                                .unit(true)
                                                .build()
                                        )
                                        .incomeHistory(true)
                                        .isActive(true)
                                        .lastName(true)
                                        .location(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedEmploymentFields
                                                .Location
                                                .builder()
                                                .city(true)
                                                .country(true)
                                                .line1(true)
                                                .line2(true)
                                                .postalCode(true)
                                                .state(true)
                                                .build()
                                        )
                                        .manager(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedEmploymentFields
                                                .Manager
                                                .builder()
                                                .id(true)
                                                .build()
                                        )
                                        .middleName(true)
                                        .startDate(true)
                                        .title(true)
                                        .build()
                                )
                                .individual(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedIndividualFields
                                        .builder()
                                        .id(true)
                                        .dob(true)
                                        .emails(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedIndividualFields
                                                .Emails
                                                .builder()
                                                .data(true)
                                                .type(true)
                                                .build()
                                        )
                                        .encryptedSsn(true)
                                        .ethnicity(true)
                                        .firstName(true)
                                        .gender(true)
                                        .lastName(true)
                                        .middleName(true)
                                        .phoneNumbers(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedIndividualFields
                                                .PhoneNumbers
                                                .builder()
                                                .data(true)
                                                .type(true)
                                                .build()
                                        )
                                        .preferredName(true)
                                        .residence(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedIndividualFields
                                                .Residence
                                                .builder()
                                                .city(true)
                                                .country(true)
                                                .line1(true)
                                                .line2(true)
                                                .postalCode(true)
                                                .state(true)
                                                .build()
                                        )
                                        .ssn(true)
                                        .build()
                                )
                                .payGroup(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPayGroupFields
                                        .builder()
                                        .id(true)
                                        .individualIds(true)
                                        .name(true)
                                        .payFrequencies(true)
                                        .build()
                                )
                                .payStatement(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPayStatementFields
                                        .builder()
                                        .paging(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPayStatementFields
                                                .Paging
                                                .builder()
                                                .count(true)
                                                .offset(true)
                                                .build()
                                        )
                                        .payStatements(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPayStatementFields
                                                .PayStatements
                                                .builder()
                                                .earnings(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPayStatementFields
                                                        .PayStatements
                                                        .Earnings
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .name(true)
                                                        .type(true)
                                                        .build()
                                                )
                                                .employeeDeductions(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPayStatementFields
                                                        .PayStatements
                                                        .EmployeeDeductions
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .name(true)
                                                        .preTax(true)
                                                        .type(true)
                                                        .build()
                                                )
                                                .employerContributions(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPayStatementFields
                                                        .PayStatements
                                                        .EmployerContributions
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .name(true)
                                                        .build()
                                                )
                                                .grossPay(true)
                                                .individualId(true)
                                                .netPay(true)
                                                .paymentMethod(true)
                                                .taxes(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPayStatementFields
                                                        .PayStatements
                                                        .Taxes
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .employer(true)
                                                        .name(true)
                                                        .type(true)
                                                        .build()
                                                )
                                                .totalHours(true)
                                                .type(true)
                                                .build()
                                        )
                                        .build()
                                )
                                .payment(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPaymentFields
                                        .builder()
                                        .id(true)
                                        .companyDebit(true)
                                        .debitDate(true)
                                        .employeeTaxes(true)
                                        .employerTaxes(true)
                                        .grossPay(true)
                                        .individualIds(true)
                                        .netPay(true)
                                        .payDate(true)
                                        .payFrequencies(true)
                                        .payGroupIds(true)
                                        .payPeriod(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPaymentFields
                                                .PayPeriod
                                                .builder()
                                                .endDate(true)
                                                .startDate(true)
                                                .build()
                                        )
                                        .build()
                                )
                                .planDependents(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPlanDependentFields
                                        .builder()
                                        .coverage(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPlanDependentFields
                                                .Coverage
                                                .builder()
                                                .enrollments(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPlanDependentFields
                                                        .Coverage
                                                        .Enrollments
                                                        .builder()
                                                        .id(true)
                                                        .type(true)
                                                        .build()
                                                )
                                                .individualId(true)
                                                .relationshipToIndividual(true)
                                                .build()
                                        )
                                        .dateOfBirth(true)
                                        .dependentId(true)
                                        .firstName(true)
                                        .gender(true)
                                        .lastName(true)
                                        .middleName(true)
                                        .ssn(true)
                                        .build()
                                )
                                .planEnrollments(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPlanEnrollmentFields
                                        .builder()
                                        .id(true)
                                        .contributions(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPlanEnrollmentFields
                                                .Contributions
                                                .builder()
                                                .employeeContribution(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPlanEnrollmentFields
                                                        .Contributions
                                                        .EmployeeContribution
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .build()
                                                )
                                                .employerContribution(
                                                    ProviderListResponse.AuthenticationMethod
                                                        .SupportedFields
                                                        .SupportedPlanEnrollmentFields
                                                        .Contributions
                                                        .EmployerContribution
                                                        .builder()
                                                        .amount(true)
                                                        .currency(true)
                                                        .build()
                                                )
                                                .frequency(true)
                                                .build()
                                        )
                                        .coverageEndDate(true)
                                        .coverageStartDate(true)
                                        .coverageTier(true)
                                        .dependentIds(true)
                                        .individualId(true)
                                        .planId(true)
                                        .status(true)
                                        .build()
                                )
                                .plans(
                                    ProviderListResponse.AuthenticationMethod.SupportedFields
                                        .SupportedPlanFields
                                        .builder()
                                        .id(true)
                                        .carrier(
                                            ProviderListResponse.AuthenticationMethod
                                                .SupportedFields
                                                .SupportedPlanFields
                                                .Carrier
                                                .builder()
                                                .id(true)
                                                .name(true)
                                                .build()
                                        )
                                        .coverageTiers(true)
                                        .deductionCodes(true)
                                        .description(true)
                                        .endDate(true)
                                        .name(true)
                                        .networkType(true)
                                        .startDate(true)
                                        .type(true)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .beta(true)
                .icon("icon")
                .logo("logo")
                .manual(true)
                .mfaRequired(true)
                .primaryColor("primary_color")
                .build()

        val roundtrippedProviderListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(providerListResponse),
                jacksonTypeRef<ProviderListResponse>(),
            )

        assertThat(roundtrippedProviderListResponse).isEqualTo(providerListResponse)
    }
}
