package org.finch.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class PayStatementTest {

    @Test
    fun createPayStatement() {
        val payStatement =
            PayStatement.builder()
                .individualId("string")
                .type(PayStatement.Type.REGULAR_PAYROLL)
                .paymentMethod(PayStatement.PaymentMethod.CHECK)
                .totalHours(123L)
                .grossPay(Money.builder().amount(123L).currency("string").build())
                .netPay(Money.builder().amount(123L).currency("string").build())
                .earnings(
                    listOf(
                        PayStatement.Earning.builder()
                            .type(PayStatement.Earning.Type.SALARY)
                            .name("string")
                            .amount(123L)
                            .currency("string")
                            .hours(42.23)
                            .build()
                    )
                )
                .taxes(
                    listOf(
                        PayStatement.Tax.builder()
                            .type(PayStatement.Tax.Type.STATE)
                            .name("string")
                            .employer(true)
                            .amount(123L)
                            .currency("string")
                            .build()
                    )
                )
                .employeeDeductions(
                    listOf(
                        PayStatement.EmployeeDeduction.builder()
                            .name("string")
                            .amount(123L)
                            .currency("string")
                            .preTax(true)
                            .type(BenefitType._401K)
                            .build()
                    )
                )
                .employerContributions(
                    listOf(
                        PayStatement.EmployerContribution.builder()
                            .name("string")
                            .amount(123L)
                            .currency("string")
                            .type(BenefitType._401K)
                            .build()
                    )
                )
                .build()
        assertThat(payStatement).isNotNull
        assertThat(payStatement.individualId()).contains("string")
        assertThat(payStatement.type()).contains(PayStatement.Type.REGULAR_PAYROLL)
        assertThat(payStatement.paymentMethod()).contains(PayStatement.PaymentMethod.CHECK)
        assertThat(payStatement.totalHours()).contains(123L)
        assertThat(payStatement.grossPay())
            .contains(Money.builder().amount(123L).currency("string").build())
        assertThat(payStatement.netPay())
            .contains(Money.builder().amount(123L).currency("string").build())
        assertThat(payStatement.earnings().get())
            .containsExactly(
                PayStatement.Earning.builder()
                    .type(PayStatement.Earning.Type.SALARY)
                    .name("string")
                    .amount(123L)
                    .currency("string")
                    .hours(42.23)
                    .build()
            )
        assertThat(payStatement.taxes().get())
            .containsExactly(
                PayStatement.Tax.builder()
                    .type(PayStatement.Tax.Type.STATE)
                    .name("string")
                    .employer(true)
                    .amount(123L)
                    .currency("string")
                    .build()
            )
        assertThat(payStatement.employeeDeductions().get())
            .containsExactly(
                PayStatement.EmployeeDeduction.builder()
                    .name("string")
                    .amount(123L)
                    .currency("string")
                    .preTax(true)
                    .type(BenefitType._401K)
                    .build()
            )
        assertThat(payStatement.employerContributions().get())
            .containsExactly(
                PayStatement.EmployerContribution.builder()
                    .name("string")
                    .amount(123L)
                    .currency("string")
                    .type(BenefitType._401K)
                    .build()
            )
    }
}
