# workflow for re-running publishing to Sonatype in case it fails for some reason
# you can run this workflow by navigating to https://www.github.com/Finch-API/finch-api-java/actions/workflows/publish-sonatype.yml
name: Publish Sonatype
on:
  workflow_dispatch:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: |
            8
            17
          cache: gradle

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish to Sonatype
        run: |
          ./gradlew publish --stacktrace
        env:
          SONATYPE_USERNAME: ${{ secrets.FINCH_SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.FINCH_SONATYPE_PASSWORD }}
          GPG_SIGNING_KEY_ID: ${{ secrets.FINCH_SONATYPE_GPG_SIGNING_KEY_ID }}
          GPG_SIGNING_KEY: ${{ secrets.FINCH_SONATYPE_GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.FINCH_SONATYPE_GPG_SIGNING_PASSWORD }}